#!/bin/sh
# ow - Obnam Wrapper that adds a few features
# Copyright (C) 2015  Andrea Bolognani <andrea.bolognani@roundhousecode.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

APP=ow

die() {
	local message

	message=$1

	echo "$APP: $message" >&2

	exit 1
}

usage() {
	echo "Usage: $APP [-p PROFILE] ..." >&2

	exit 1
}

main() {
	local profile
	local send_emails
	local conf
	local obnam_conf
	local log_file
	local opts
	local rest
	local rc

	# Parse command line
	while test $# -gt 0
	do
		case "$1"
		in
			-p)
				shift
				profile=$1
				test "$profile" || usage
				;;
			-m)
				send_emails=yes
				;;
			*)
				break
				;;
		esac
		shift
	done
	rest=$@

	test "$profile" || profile=default

	# Configuration file for ow itself
	conf="$HOME/.$APP.conf"
	test -f "$conf" || die "$conf: No such file or directory"
	. "$conf" || die "$conf: Error while loading file"

	# Configuration file for obnam
	obnam_conf="$HOME/.obnam.$profile.conf"
	test -f "$obnam_conf" || die "$obnam_conf: No such file or directory"

	# Switch to a safe directory because obnam includes the current
	# directory to the list of root directories and we don't want to
	# end up including random stuff in the backup because of this
	cd /tmp || die "Could not switch to /tmp"

	opts="--config=$obnam_conf"

	test "$send_emails" -a "$rcpts" && {
		log_file=$(mktemp -p /tmp "$APP.XXXXXXXXXXXX")
		opts="$opts --log=$log_file"
	}

	# Run obnam
	echo Running obnam $opts $rest
	obnam $opts $rest
	rc=$?

	test "$send_emails" -a "$rcpts" && {
		# Send emails, including all useful information in the
		# subject and the full log in the body
		mail \
			-s "$APP@$(hostname -f) ($profile), rc=$rc" \
			-r "$APP@$(hostname -f)" \
			$rcpts <"$log_file"
		rm -f "$log_file"
	}

	return $rc
}

main "$@"
